### PR TITLE
Updates our team!

### PR DESCRIPTION
**Pull request by krashanoff**
This will be the PR that adds all of our faces and names (with permission) to the TeachLA website. I'll be updating it as more people send me their picture in the days to come.

### CODE REVIEW

**Comment by malsf21** [comment]
On this, could we somehow divvy-up the page a bit more for board, instructors, and dev team? Not sure how to do this and also handle cross-over though - open to any thoughts!

**Comment by krashanoff** [comment]
Yeah actually, I was thinking of doing the same thing. I was just worried about making the changes on here if someone were to add their own image via another PR and make some whack merge conflict - crossover, like you mentioned. I think I'll just ask everyone personally for their information and then carry out the legwork on my own.

**Comment by krashanoff** [comment]
Probably going to resize all images for our team to 512x512 after their photos are all in.

**Comment by krashanoff** [comment]
Look at all those beautiful faces! As a note on the commit history: it appears as though Regina added the commit on account of merging from her master (I was checking her changes the other day).

**Pull request merged**
