### PR TITLE
Adds Zihan Xue to Team Page :)

### PR DESCRIPTION
**Pull request by MDZHX**
Added me (Zihan Xue) to Team Page :P.
Files added are `zxue.md` and ~`zxue.png`~ `zxue.jpg`.

### CODE REVIEW

**Review by krashanoff — COMMENTED** [review]
Heya Zihan! Not Matt, but this looks good save for the profile image size. On slower network connections your profile image will take an appreciable amount of time to load. Manually throttling my connection to 4G speeds, it took about 42 seconds:



Compressing the image to 512x512 should do the trick. We do have a bot that automatically does this after merging, but I thought I should bring it to your attention in case you wanted to change the cropping so it had better visibility at smaller sizes, for example. Other than that, you're good to go. Thanks Zihan!

**Comment by MDZHX** [comment]
Hi Leo,

Thanks for the reminder! I'll fix the image now :)

**Review by krashanoff — APPROVED** [review]
1.15MB is still rather large, so reducing the size once more prior to merging would be ideal. Aside from that, I see no issue. Worst case scenario, the image bot will file a PR should optimizations be in order. Thanks for the quick addressal!

**Comment by MDZHX** [comment]
I resized the image to reduce the size a little bit more :) Also, I wonder what would be an ideal size for an image like this?

**Comment by krashanoff** [comment]
Thanks for reducing the size! To answer your question, as mentioned in the earlier review, we use 512x512 for our profile images. This said, that's just a quick and general fix. In a production website, usually you'd want to use [responsive images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) to gradually load in your full-quality images.

**Pull request merged**
