### PR TITLE
Adds Jiin to the team page!

### PR DESCRIPTION
**Pull request by doubleiis02**
added `jiinkim.md` and `jiinkim.jpg`
please add me to the team page :D

### CODE REVIEW

**Comment by krashanoff** [comment]
Heya Jiin, just wanted to let you know that your profile image is a `.jpg`, so you've got to update it before this is good to merge. Glad to have you on our team!

**Comment by doubleiis02** [comment]
> Heya Jiin, just wanted to let you know that your profile image is a `.jpg`, so you've got to update it before this is good to merge. Glad to have you on our team!

Oops, I meant to write 'jiinkim.jpg' in the description. Should I change the file to png? It seems like most of the other profile pictures in the file are jpg.

**Comment by krashanoff** [comment]
While `.png` is generally a superior image format, `.jpg` is fine for web. Either one works.

**Comment by doubleiis02** [comment]
Cool, the request should be good to merge then.

**Comment by krashanoff** [comment]
> Should I change the file to png? It seems like most of the other profile pictures in the file are jpg.

Ahhh I should clarify. The file extension should match what you have listed. The file that was uploaded was a `.jpg`, but your team page references `.png`. So you can either:
1. Change your image file to a `.png`
*or*
2. Change your team page file to reference the `.jpg`.

**Comment by doubleiis02** [comment]
Oh ok my bad, thanks for clarifying. Should be good now!

**Review by malsf21 — APPROVED** [review]
LGTM 👍 , welcome officially to the team 😎 

(please squash merge when you merge this PR!)

**Pull request merged**
