### PR TITLE
Sketching out a "Classes" and "Schools" Page, + new CTA Include

### PR DESCRIPTION
**Pull request by malsf21**
This PR sets the groundwork for two new pages:

* a "classes" page, which lists all the classes we've ever taught, including learning goals, lead instructors, and links for more information
* a "schools" page, where you can see all of our partnered schools

For now, I've finalized all of the content I want on these two pages (though the content they link to, like course outlines & learning paths, are still WIP). We'll have to revisit schools later when the school year starts.

In addition to those two new pages, I've also created a Jekyll include, `contact-cta.html`. This is copy (the links which we'll update soon) intended to pad out the space between the last content on a page and the footer, with a CTA to contact us. LMK what you think.

Finally, I made several small site-wide design changes:

* icons inside of buttons now have an explicit `margin-right` to guarantee spacing
* `line-height` increased to `1.25` for `<p>` and `1.5` for `ul > li` for better readability

Preview here: https://deploy-preview-44--unruffled-perlman-fe51d2.netlify.app/classes

### CODE REVIEW

**Comment by malsf21** [comment]
At the moment, this is the generic layout that I want to have for this page. @krashanoff @vohndernet, can I get some quick feedback on what y'all think about the general layout? I will still have to update some copy and add pages for some of the dead links.

**Comment by vohndernet** [comment]
It looks good! Putting side-by-side the image with the class description makes the layout clean, and I really like the hover colors over the buttons.

Something that’d be nice would be to add more color. Right now the page has a lot of the white palette background, and the classes themselves only have a thin green border to separate them. Maybe to have more of a focus, accentuate the borders of the class, or add more green somewhere? Alternating background colors is an idea, if we’re feeling daring (perhaps too daring), but overall, I’m for whatever makes the classes more distinctive. What do you think? (tdlr; more color, make the classes stand out)

Also small detail, but I’m unsure if I like how the img moves when you expand the learning goals for a class. The re-centering is a nice touch, but I always get the urge to collapse the text just so the image moves back. That might be a nitpick habit on me, though.

( extra small detail: could do with more spacing between the last class and the footer. Otherwise, it all looks very nice.)

**Comment by krashanoff** [comment]
For feedback on the general layout, I think this is looking good, though on desktop I think it could do with a little more above the fold. With a small number of classes, having this sort of layout works well, but should we add more, it will get more cumbersome to browse which classes we offer. If I were a school interested in what TeachLA can offer me, then I'd probably like an overview of offered material to be the first thing I see when clicking on the classes page.

When expanding the learning goals, I can't say I like that the image for each class moves with it to realign:
Peek 2020-06-26 11-24

**Comment by malsf21** [comment]
Thanks for the feedback y'all! I'll definitely see what I can do about the image-centering shenanigans and adding more space between the last card and the footer.

@vohndernet I do agree that there isn't much going on with the colors and the background of the card! I'll do a bit more thinking and see what I can do, though I'll also touch base with Tomoki and the ACM Design team and see what their content guidelines are. That was a good piece of feedback, thank you for letting me know!

**Comment by malsf21** [comment]
Okay, implemented the footer and image related feedback suggested above. Haven't forgotten about making the page more colorful, but I think ACM Design will have a ready-made component for us once they're done the rework, so I'm going to hold off on that for now.

Looking to merge this page (and the new schools page I created, `/schools`) now. Can I get any more final feedback and/or a code review @vohndernet and @krashanoff? No rush!

**Comment by malsf21** [comment]
> As for why this isn't an immediate approval, something that kind of catches me is the "interested in working with us?" portion at the bottom of the page. I feel like it needs to be something the viewer sees early in the page, but moving it to the top would really gnarl the clean above-the-fold that you have. I just wanted to see what you thought about this.

Gotcha, I know what you mean. I'll add some extra contact info to the above-the-fold. The plan with the CTA is to pad out the bottom space and a "I'm done scrolling through, what do I do" kind of visual element. Thoughts?

**Comment by vohndernet** [comment]
The changes look good! Something I realized about the buttons as I'm looking at the page, it'd be nicer to have extra spacing between the icon and the words that follow, so they're less close to each other. (Though this is less a class page change and more a website-wide style change, but something good nonetheless)

Also caught a minor consistency issue with the learning goals–– the Intro to AI and ML has its bullet points capitalized, whereas the previous LGs were all lower-case.

**Comment by malsf21** [comment]
Solid feedback Nhi, thanks! I'll implement it now.

> it'd be nicer to have extra spacing between the icon and the words that follow

Agreed!

> the Intro to AI and ML has its bullet points capitalized, whereas the previous LGs were all lower-case.

Good catch, I'll fix that.

**Comment by malsf21** [comment]
@vohndernet let me know if the following changes were what you had in mind!

**Comment by malsf21** [comment]
Also just jacked up the `line-height` per convo w/ @krashanoff

**Comment by krashanoff** [comment]
Definitely looking more readable. Thanks for the corrections Nhi and thanks for the changes Matt. Things are looking good to me. Any input @vohndernet?

**Comment by malsf21** [comment]
Great, going to merge. Going to start getting more info from our classes & curriculum team. Thanks for all the feedback!

**Pull request merged**
