### PR TITLE
Added Matthew Nieva and profile picture to teams page

### PR DESCRIPTION
**Pull request by matthewcn56**
Added mnieva.md and mnieva.jpeg

### CODE REVIEW

**Review by malsf21 — COMMENTED** [review]
Is there a reason you've modified `Gemfile.lock`?

**Comment by matthewcn56** [comment]
> Is there a reason you've modified `Gemfile.lock`?

it automatically did it. Do I have to update my ruby?

**Comment by matthewcn56** [comment]
I went back to master branch and ran `bundle` again to see if I forgot any dependencies, but it automatically deleted wdm again. wdm is the windows directory monitor dependency, so I'm guessing that it got deleted since I'm using a Mac machine?

**Review by malsf21 — APPROVED** [review]
LGTM 👍 

(please squash merge if you can!)

**Pull request merged**
