### PR TITLE
Update ezhong.md to match new github handle

### PR DESCRIPTION
**Pull request by evanzhong**
I changed my github username so just wanted to update any old references so they wouldn't go to a 404 page.

### CODE REVIEW

**Review by malsf21 — APPROVED** [review]
LGTM! I'll let you do the honours 🎉

**Comment by evanzhong** [comment]
> LGTM! I'll let you do the honours 🎉

Don't believe I have write access @malsf21, so will not be able to merge on my end.
image

**Comment by malsf21** [comment]
@evanzhong think I've updated your team description, let me know!

**Comment by evanzhong** [comment]
> @evanzhong think I've updated your team description, let me know!

Thanks matt! Merging...

**Pull request merged**
