### PR TITLE
Adds Varsha to the team page!

### PR DESCRIPTION
**Pull request by varshah2000**

### CODE REVIEW

**Review by krashanoff — CHANGES_REQUESTED** [review]
Hey Varsha! Glad to have you on the team :smile:

While one *could* merge this along with your previous PR #104 to produce the effect of making both changes at the same time, it will make life easier for versioning if you could consolidate both your changes to this single PR. The way that you can do this is by simply editing the files of concern on the `varshah2000-patch-2` branch. The changes will show up in this PR, and will then allow both the new about page _and_ your image to be merged simultaneously. Thanks!

**Comment by varshah2000** [comment]
Hi Leo, 

Not gonna lie, it took me a while to figure out LOL. Hopefully I did what you were asking though, if not please let me know :)

**Review by malsf21 — CHANGES_REQUESTED** [review]
Hey Varsha,

No worries at all if it's been confusing - learning git and GitHub is tough! I don't want this to be a struggle though, so let us know if you're running into any problems.

Just as a quick note: your `vhunter.md` file is in the wrong place, it needs to be in the `_team` folder (right now it's top-level in the repository). Unfortunately, that means it won't be rendered in our site! Do you mind fixing that? If you're having problems, feel free to ask us if you want help!

P.S. are you testing the site locally with `bundle exec jekyll serve`? It makes it easier to test if your changes work!

**Comment by varshah2000** [comment]
Hey Matt! 

I just relocated the file into the _team folder and now see myself on the team page! Please let me know if I need to do anything else!

**Review by malsf21 — APPROVED** [review]
Hey Varsha! Overall this looks good, I think we can merge it. Welcome (officially) to the team!

P.S. your image isn't square, which is _normally_ what we ask for, so it'd be great if you could update it some other time - but for now, I think we'll merge. Thanks for all your work on this!

**Pull request merged**
