### PR TITLE
Matthew Yoshida teams profile page

### PR DESCRIPTION
**Pull request by matthewcyy**

### CODE REVIEW

**Review by krashanoff — COMMENTED** [review]
Hey Matthew! Welcome to Teach LA. I am not Matt, but I can handle review for this. Only comment is the dimensions of your photo. We usually crop profile photos to 512x512 so that the flow of the teams page is regular. A portrait photo throws things a little out of whack.

image

Aside from this, things look good.

**Comment by matthewcyy** [comment]
Ah I see, thank you for the quick response then Leo! I appreciate the
feedback.

**Comment by malsf21** [comment]
Yup, other than that this looks good to merge! Just push a commit to update this branch with a new image whenever you're free 😊

**Comment by matthewcyy** [comment]
Ok I believe I was able to crop the photo, let me know if there's anything else I have to do! Also, for future's reference, I noticed that when I updated the image it wasn't in it's own pull request and it's just a part of this same one. Is that always the case if we edit a file from a pull request that has already been made?

**Review by krashanoff — APPROVED** [review]
Looks good to me! Thanks Matthew.

> I noticed that when I updated the image it wasn't in it's own pull request and it's just a part of this same one. Is that always the case if we edit a file from a pull request that has already been made?

Yes, this is the case. A pull request is kind of like a rolling request to make changes, so you can always push on new changes to the same request in response to feedback.

**Review by malsf21 — APPROVED** [review]
LGTM as well. I'll let you do the honours to merge Matthew, just makes sure to use the "squash and merge" option!

**Pull request merged**
