### PR TITLE
Adjust blog post width, centers content

### LINKED ISSUE #126: Adjust blog post max-width
Thanks to @surreally for bringing this up - we should enforce single columns to have between 50-70-ish rem, depending on how things look with our current font & layout.

### PR DESCRIPTION
**Pull request by nendow02**
Changed post-container max-width from 50 rem to 40rem, centers content.

Closes #126.

### CODE REVIEW

**Review by malsf21 — COMMENTED** [review]
Hey Nathan, thank you for working back and forth on this seemingly trivial change! I definitely think we've captured more of a Medium feel, but I'm not sure if the content is still wide enough.

Would love to get a second opinion. I know @surreally brought this up, so I'd love to get his thoughts on this - also going to cc @krashanoff and @lishamohan and see if they have any thoughts. Should we go `40em`/`40rem` instead?

**Review by lishamohan — COMMENTED** [review]
Hmm yeah I'm leaning towards `40em`/`rem`

**Review by krashanoff — COMMENTED** [review]
I agree with Lisha, `40rem` seems to be the call imo.

**Comment by malsf21** [comment]
Hm okay, @nendow02 do you mind trying `40rem`/`40em` and see what gives you better results? We can then compare it to live, which is `50rem` right now.

>  I will add, though, that the blog landing page will not conform to this width, and might be a bit offputting to some users. Super nitpicky detail, but thought it may be worth chewing on.

We can always adjust the styling on the landing page as well if we'd like.

Something also that I'll point out is that the rest of the blog post (i.e. not just the content, but the footer) doesn't abide by those rules - may be something that we should think about as well.

**Comment by nendow02** [comment]
Okay I changed max-width to 40em now

**Comment by malsf21** [comment]
cc: @krashanoff @lishamohan

**Comment by lishamohan** [comment]
That looks good! I agree that the author footer width should probably match though

**Comment by krashanoff** [comment]
+1 off Lisha. Other than that, LGTM.

**Comment by surreally** [comment]
1. 40em looks good, max character count on one line seems confined to about 90 now because of the font size, which is much more readable compared to >100. I like narrower columns (80 char max) from reading in my browser too much but that's just a preference.
2. We did break something: Screen Shot 2020-11-10 at 2 16 19 AM 
However, this is a problem we have on narrower viewports even if we didn't make the 40em change. It just wasn't obvious when it was 50rem on desktop. I propose adding horizontal scroll to code boxes to remedy the issue, since reformatting code blocks is not the best thing to do.
3. New issue inspired by this review: we should pick a monospace font in our design for the code elements. Right now it defaults to browser specified stylesheets, and this irked me a bit. Screen Shot 2020-11-10 at 2 44 11 AM 
I suggest a monospace font with varied weights close to those of open sans so in links containing code fragments it will look great. [Fira Mono](https://bboxtype.com/typefaces/FiraMono/#!layout=specimen) looks good to me. Screen Shot 2020-11-10 at 3 10 49 AM

Cool reference: [Summary of key rules at Practical Typography](https://practicaltypography.com/summary-of-key-rules.html)

**Comment by malsf21** [comment]
@surreally, thank you for the feedback on the monospaced font and horizontally-scrolled code blocks - I fully agree on both fronts! It's a bit out-of-scope for this PR, but I'll create a new issue for it and more than happy to assign it to anybody who's interested. Definitely agree that it's pretty standard for most web code blocks (especially those that are markdown generated), something we've definitely slipped up on before.

addendum: should we softwrap our `pre`/`code` blocks?

**Review by malsf21 — APPROVED** [review]
For now, I think this is good to merge - thank you for all your hard work on this @nendow02! I'll let you do the honours, but please use the "squash merge" option if possible.

Note: this ruins the git blame for the file :/ I'm surprised that git couldn't get a good diff in tbh!

**Pull request merged**
