### PR TITLE
Updates several unDraw illustrations with new palette, redraws classes images, and adds Drew to teams page

### PR DESCRIPTION
**Pull request by Gautier404**
Added and modified images on the class page. Changed colors of other unDraw images. Added Drew to the team page.

### CODE REVIEW

**Review by krashanoff — DISMISSED** [review]
Drew, this is looking great! Who knew we'd be getting a designer extraordinaire in the dev team?

Only change that needs to be done before merging is an update of the alttext for the images that you redesigned. Thanks for all your work!

**Comment by Gautier404** [comment]
I just added alt descriptions for all the images on the class page, using the method matt taught with the "decorative" key word.

**Review by malsf21 — APPROVED** [review]
This all looks good to me, thanks Drew! Absolutely love the new illustrations, and I'm excited to have you join our team 😄 

(please use the squash merge option instead of the merge commit!)

**Review by krashanoff — APPROVED** [review]
LGTM!

**Pull request merged**
