### PR TITLE
Add Farrah's profile to site

### PR DESCRIPTION
**Pull request by ayfarrah**
Pronouns field is also updated in this commit

### CODE REVIEW

**Review by mattxwang — CHANGES_REQUESTED** [review]
One last ask - as mentioned in the team docs, all of the images should be square (and ideally < `1000px`) - do you mind resizing your image to fit?

**Comment by ayfarrah** [comment]
oops sorry must have missed that - image size is updated!

**Review by mattxwang — APPROVED** [review]
LGTM! Please merge using the "squash and merge" option; welcome (officially) to our team 😊

**Comment by ayfarrah** [comment]
done!! thanks Matt :)

**Pull request merged**
