### PR TITLE
Updated About page and changed styling

### PR DESCRIPTION
**Pull request by TracyZhao24**
Updated the table on the About page with new classes at Emerson and Short Ave. Redesigned the table to black-on-white for text values, and alternated the border styling instead. Modified .schedule-table in _sass/basics.scss and about.html.

### CODE REVIEW

**Review by malsf21 — CHANGES_REQUESTED** [review]
Hi Tracy,

Thanks for these changes! Overall, I think it's looking pretty good. My only comment - what if we tried using a (single) solid black border instead? Not sure how I feel about the double-border. We can compare the styles and see what looks best (and obv if you've got another solution, totally down to see it 😊 )

Other than that, this is good to merge! Let me know if you have any q's!

**Comment by TracyZhao24** [comment]
Hi Matt!

I can change it to a single solid black border instead. Should I make
another pull request?

- Tracy

**Comment by malsf21** [comment]
Hey @TracyZhao24, sounds good! You can actually just push a new commit to this branch (e.g. `git add .`, then `git commit -m "..."`, then `git push`) and the PR will automatically update!

**Comment by TracyZhao24** [comment]
Done! It's a single border now.

**Review by malsf21 — APPROVED** [review]
Great Tracy, this looks better already! I'll let you do the honours of merging; please use the "squash merge" option!

**Pull request merged**
