### PR TITLE
New Footer!

### PR DESCRIPTION
**Pull request by MDZHX**
Draft of the new footer, created the basic layout :)
Followed the Figma draft from ACM Design, with some minor adjustments.

### CODE REVIEW

**Comment by mattxwang** [comment]
This is on my radar! Will get to it tomorrow/before dev team meeting. Feel free to work on the blog post in the meantime if you'd like!

**Review by mattxwang — CHANGES_REQUESTED** [review]
In general, the code all looks good! Just some thoughts on design and columns:

* can we change **Internal** to **Members**? I think I'm going to change the **Docs** page's titles (maybe **Static Site Setup** and **Add Yourself to the Team Page**) plus add the **Join Us** and new **Dev Resources** pages
* I think we mentioned this earlier, but we should have some way to put our social media + contact information here!
* a bit nitpicky, but if possible it'd be great if we can get **Events** to break one line per event: maybe changing the text to "AI Ethics" and "Cyber Day", or through a style change.

If I had to be honest, I'm still a bit finicky on exactly which headings should have what content. It looks good so far though!

**Comment by MDZHX** [comment]
Thanks for the review! I'll soon change the text. For the social media part, are there requirements of which kinds of icons (e.g. FB, email) we should use?

**Comment by mattxwang** [comment]
> Thanks for the review! I'll soon change the text. For the social media part, are there requirements of which kinds of icons (e.g. FB, email) we should use?

Hm, no specific requirements per se, as long as the color is accessible. Feel free to play around with whatever you prefer; we often use [Font Awesome](https://fontawesome.com/)!

**Comment by mattxwang** [comment]
One other thing I'll note - it may be worthwhile to loop in #271 in here too! I definitely think a Classes subfooter should be one of our main ones!

**Comment by MDZHX** [comment]
Hi Matt! It took me some time to figure out the appropriate liquid syntax for breaking all the generated links into different columns, but now the auto-generation functionality is implemented :) That being said, a major styling problem needs to be solved before deploying.

### Updates:
- Added/changed some text as we previously discussed.
- Added social media + contact information.
- Programmatically generate links for projects & classes, with 5 links max per column.
- Update/remove links to reflect changes in `master`.

### Although the footer now works functionally, there is still a major styling problem:
- Some link texts are pretty long and couldn't fit into one line.
- This is somewhat hard to read, and it also made some columns really long.
- (Yes, the "Classes" section contains only five items, but it looks reaaaally long. Similar things also happen in "Projects" and "Members").

### Last but not least, some content-wise things to note
- Some projects have no links, so no `href` attributes for them.
- The mail icon and the text link currently refer to the same email address, not sure if that would be somewhat redundant.
- Since the `docs` link has been removed from the footer, there's no way to get to the original docs page anymore.
  - Although we broke the original `docs` link into several other links, there are still some unique instructions on the docs page itself, so I'm not sure if we still need the original docs page.
- Should "© ACM @ UCLA 2019" be changed to "© ACM @ UCLA 2021"?
- We changed "Internal" to "Members", but I think in terms of the current content it's more like "(Dev Team) Members". This might be kind of misleading.
  -  One particular thing is the "Join Us" link under "Member". Since all other links under "Member" are dev-related, "Join Us" now links to the dev team form. Not sure if it would be better to link to the general join page.
- Besides, do you think any other adjustments on layout/content are needed?

I'm sorry that this is a lot of detail, especially when you are transitioning out. If you think it would be better, we can hand over the rest of this PR to Vivian. Thanks again for handling the transition work!

**Review by mattxwang — CHANGES_REQUESTED** [review]
Hi Zihan,

Thanks for all your work on this so far! The footer is really coming together, which is lovely, and I always appreciate your in-depth comments. Let me see if I can address each one!

> Some link texts are pretty long and couldn't fit into one line.

Great point. I think some of these links could be shortened: for example, our class titles could be something like "Intro to Python", "Intro to AI & ML", "Intro to React Native", or even just "Python", "AI & ML", and "React Native". This may involve adding a new YAML field (something like a `short_title`?). Let me know what you think here!


> The mail icon and the text link currently refer to the same email address, not sure if that would be somewhat redundant.

I personally think that you should always write out the email address, since mail "links" (with the `mailto:` protocol) are often confusing for people who don't use computers frequently. Beyond that, up to you and Vivian on how much detail you want to include for each social (email, facebook, github, Linkedin).

> Some projects have no links, so no href attributes for them.

Great catch! Three options I see:

* don't include them
* use their github repo link instead
* link to the card on the dev page with a hash link, i.e. `#`

This is something that maybe @vivianha534 can chime in on.

> Since the docs link has been removed from the footer, there's no way to get to the original docs page anymore.
Although we broke the original docs link into several other links, there are still some unique instructions on the docs page itself, so I'm not sure if we still need the original docs page.

We can probably just make a new link, "docs home" or something. The whole docs situation is a little bit messy, @vivianha534 may be able to talk to you about her vision for it.

> Should "© ACM @ UCLA 2019" be changed to "© ACM @ UCLA 2021"?

No, because copyright dates are for when the copyright is first established. If you want to keep the date current, we can do 2019-2021!

> "Join Us" now links to the dev team form. Not sure if it would be better to link to the general join page.

Re: this, I personally think the join us link should link to the general join page. The idea of the other docs-related things is that they're specifically for people not on the dev team, so they know how to add themselves to the static site, etc. If anything, I'd also shuffle Join us to the very top of this category.

> Besides, do you think any other adjustments on layout/content are needed?

On my end, nothing jumps to mind - as always, you've done a great and thorough job on this! I would also tag in @vivianha534 if she has anything to add, and she can leave the final approving review.

**Comment by vivianha534** [comment]
Hey Zihan! The footer looks like it's coming along really well! Thanks for all of the work you've put done c:


>The mail icon and the text link currently refer to the same email address, not sure if that would be somewhat redundant.

This is a really good observation, I think this comes down to what we would want our final design to look like and how we want our user to interact with our footer.

I believe that most of Teach LA's communication with our schools, and partners are done via email, so it would be nice to have our full email in the footer. So one thing we can do to not make the full email not look so out of place is we can add a linkedin icon, and have our linkedin, facebook, and github icons all be in one row above our mail icons and full gmail.

Also if we do it this way, you would no longer need to have the mail icon, and the gmail as seperate list items, and you can instead just have them both be in one list item, which would address the issue of redundancy.

Just one more thing on the icons, I think from an accessibility stand point, it would be really helpful if you were able to enlarge the icons, since they're kind of small right now.

>Some projects have no links, so no href attributes for them

For this part I think it might be worth scrapping the Projects section of the footer altogether. I noticed that under the "Our Work" section, we have a link that directs us to the dev page where all of the projects are. I think we could just change Dev -> Dev Projects, and get rid of the projects section altogether. I think this would also help resolve some of the styling issues that we currently have. Also, I think redirecting to the dev page would result in a better user experience because if a user is looking for a project, but forgot what the project name was, they could look at the summaries provided on the dev page.

Also as our learning labs continue to grow, I don't think it would be very sustainable to list out every single project in our footer.

>Since the docs link has been removed from the footer, there's no way to get to the original docs page anymore. Although we broke the original docs link into several other links, there are still some unique instructions on the docs page itself, so I'm not sure if we still need the original docs page

Ooo this is a great point! Let me look into the routing of the site a little more before I give you an answer. I'll try to get back to you before the end of tomorrow.

>"Join Us" now links to the dev team form. Not sure if it would be better to link to the general join page.

I agree with Matt, but also from a UI/UX stand point, it would probably be confusing for our header "Join us" button to point at one thing, and the "Join us" link in the footer to point to another thing. In general I think, it would be best to keep all join us buttons/links pointing to the general join page.

>Besides, do you think any other adjustments on layout/content are needed?

I totally agree with Matt - this looks super good! You did a really good job with this ticket, I think there's just some minor things that need to be changed before we can merge it into master!

**Action Items:**
- Go ahead and create shortened class titles (per Matt's suggestion)
- Change column 1 to have the following rows
     - row 1 - ACM Teach LA
     - row 2 - facebookIcon githubIcon linkedinIcon
     - row 3 - mailIcon acmteachla@gmail.com
     - row 4 - acm copyright
- Please enlarge the icons
- Go ahead and remove the Projects section from the footer and change the "Dev" in "Our Work" to "Dev Projects"
- I'll get back to you by the end of tomorrow, end of Thursday latest about how to handle the docs link
- change the "Join Us" in "Members" to point to the general interest form

But yeah, really good job, the footer is looking really nice!

**Comment by MDZHX** [comment]
Thanks for the review and suggestions from both of you! I've made changes regarding all of the issues we discussed, except for the docs page one. Take a look if you want, before adding final changes on the docs page and merging :)

**Comment by vivianha534** [comment]
Hey Zihan, thanks for all of the work you've done! This footer looks amazing! Sorry I didn't get back to you yesterday, about the docs page. I think for now we can go ahead and leave the original docs page because we already have the majority of the useful content in the general docs page as links in the footer.

In case you were wondering what would happen to the original docs page since we currently have no way of accessing it from the site, I'll be creating a ticket to create a button on the dev page that will link to our docs. You don't have to worry about this for this footer ticket, but I thought I would mention it since you brought up the great point that we currently can't access our docs page from our site!

**Review by vivianha534 — APPROVED** [review]
This looks great!

**Pull request merged**
